/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package opencast.software;

public class FizzBuzzApp {

    public static void main(String[] args) {
        System.out.println("FizzFuzz app running...");
        FizzBuzz fizzBuzz = new FizzBuzz();
        for (int i = 0; i < 100; i++) {
            System.out.println(fizzBuzz.run(i));
        }
    }
}
