/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'davicres' at '12/05/16 13:16' with Gradle 2.12
 *
 * @author davicres, @date 12/05/16 13:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
