/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'davicres' at '08/04/16 12:41' with Gradle 2.12
 *
 * @author davicres, @date 08/04/16 12:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
